# object confidence threshold
confidence_threshold: 0.45

# NMS IoU threshold (the smaller the value, the fewer boxess will remain after the NMS)
# note: some models (e.g. DINO) don't have the NMS
nms_iou_thresh: 0.65

# IoU threshold to filter out predictions that significantly overlap with ground truth objects
# (the greater the value, the fewer predictions will remain)
# If the value is 0.0, no filtering will be done
existing_objects_iou_thresh: 0.0
