# object confidence threshold
confidence_threshold: 0.45

# NMS IoU threshold (the smaller the value, the fewer boxess will remain after the NMS)
# note: some models (e.g. DINO) don't have the NMS
nms_iou_thresh: 0.65

# NMS IoU threshold for the boxes that have ground truth
# note: it can slow down the post-processing
nms_iou_thresh_with_gt: 0.0
