# object confidence threshold
confidence_threshold: 0.45

# NMS IoU threshold (the smaller the value, the fewer boxess will remain after the NMS)
# note: some models (e.g. DINO) don't have the NMS
nms_iou_thresh: 0.65

# NMS force flag
# (if True, the NMS will be forced even if the model doesn't have it)
force_nms: False
